package ru.fifth.horror.client.gui;
import net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking;import net.fabricmc.fabric.api.networking.v1.PacketByteBufs;import net.minecraft.client.gui.DrawContext;import net.minecraft.client.gui.screen.Screen;import net.minecraft.client.gui.widget.TextFieldWidget;import net.minecraft.entity.Entity;import net.minecraft.network.PacketByteBuf;import net.minecraft.text.Text;import ru.fifth.horror.client.AnimationCatalog;import ru.fifth.horror.network.FifthNetworking;import java.util.*;
public final class AnimationConditionScreen extends HorrorScreen{private final Screen parent;private final int entityId;private final String uuid;private TextFieldWidget idField,valueField,search;private String type="player_near",selected="";private int page;private String status="";public AnimationConditionScreen(Screen p,Entity e){super(Text.literal("FIVEN / УСЛОВИЯ АНИМАЦИЙ"));parent=p;entityId=e.getId();uuid=e.getUuidAsString();}
@Override protected void init(){beginHorrorInit();int w=contentWidth(520),x=(width-w)/2,y=safeTop(),g=6,bh=20;idField=horrorField(x,y,(w-g)/2,bh,"rule_1",64);valueField=horrorField(x+(w+g)/2,y,(w-g)/2,bh,"6",16);search=horrorField(x,y+28,w,bh,"Поиск анимации...",96);search.setChangedListener(v->{page=0;refresh();});addDrawableChild(HorrorButton.builder(Text.literal("Условие: игрок рядом"),b->{type=type.equals("player_near")?"timer":"player_near";b.setMessage(Text.literal(type.equals("player_near")?"Условие: игрок рядом":"Условие: таймер (тики)"));}).dimensions(x,y+56,w,bh).build());for(int i=0;i<5;i++){final int r=i;addDrawableChild(HorrorButton.builder(Text.literal("-"),b->choose(r,b)).dimensions(x,y+84+i*24,w,bh).build());}addDrawableChild(HorrorButton.builder(Text.literal("<"),b->{page=Math.max(0,page-1);refresh();}).dimensions(x,y+208,50,bh).build());addDrawableChild(HorrorButton.builder(Text.literal("Сохранить условие"),b->save()).dimensions(x+56,y+208,w-112,bh).build());addDrawableChild(HorrorButton.builder(Text.literal(">"),b->{page++;refresh();}).dimensions(x+w-50,y+208,50,bh).build());addDrawableChild(HorrorButton.builder(Text.literal("Назад"),b->client.setScreen(parent)).dimensions(x,y+236,w,bh).build());refresh();}
private List<AnimationCatalog.Entry> list(){String q=search==null?"":search.getText().toLowerCase(Locale.ROOT);return AnimationCatalog.INSTANCE.entries().stream().filter(e->q.isBlank()||(e.name()+" "+e.description()).toLowerCase(Locale.ROOT).contains(q)).toList();}
private void refresh(){var l=list();int max=Math.max(0,(l.size()-1)/5);page=Math.min(page,max);int start=page*5,idx=0;for(var ch:children())if(ch instanceof net.minecraft.client.gui.widget.ClickableWidget b&&b.getY()>=safeTop()+84&&b.getY()<safeTop()+204){int p=start+idx++;if(p<l.size()){var e=l.get(p);b.setMessage(Text.literal(e.name()+" §8— §7"+e.description()));b.active=true;}else{b.setMessage(Text.literal("-"));b.active=false;}}}
private void choose(int r,net.minecraft.client.gui.widget.ClickableWidget b){var l=list();int p=page*5+r;if(p<l.size()){selected=l.get(p).name();status="Выбрано: "+selected;}}
private void save(){if(selected.isBlank()){status="Выбери анимацию.";return;}double v=6;try{v=Double.parseDouble(valueField.getText());}catch(Exception ignored){}PacketByteBuf b=PacketByteBufs.create();b.writeString(idField.getText(),64);b.writeString(uuid,64);b.writeString(selected,256);b.writeString(type,32);b.writeDouble(v);ClientPlayNetworking.send(FifthNetworking.SAVE_ANIMATION_CONDITION,b);status="Условие сохранено.";}
@Override public void render(DrawContext c,int mx,int my,float d){horrorBackground(c);c.drawTextWithShadow(textRenderer,"ID правила",(width-contentWidth(520))/2,safeTop()-10,0xFFB69F97);if(!status.isBlank())c.drawCenteredTextWithShadow(textRenderer,status,width/2,height-safeBottom()-14,0xFFD99090);super.render(c,mx,my,d);}}
