package ru.fifth.horror.client;

import com.mojang.blaze3d.systems.RenderSystem;
import net.fabricmc.fabric.api.client.rendering.v1.CoreShaderRegistrationCallback;
import net.fabricmc.fabric.api.client.rendering.v1.WorldRenderEvents;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.gl.ShaderProgram;
import net.minecraft.client.render.*;
import net.minecraft.client.util.math.MatrixStack;
import net.minecraft.entity.Entity;
import net.minecraft.util.math.Box;
import net.minecraft.util.math.Vec3d;
import org.joml.Matrix4f;
import ru.fifth.horror.FifthMod;
import ru.fifth.horror.effect.EntityEffectManager;

import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Shader-driven horror entity overlays. Geometry is generated by the mod and rendered through
 * a dedicated core GLSL shader; no vanilla ParticleEffect/ParticleManager is involved.
 */
public final class EntityEffectRenderer {
    private static final Map<UUID, EntityEffectManager.Config> CONFIGS = new ConcurrentHashMap<>();
    private static ShaderProgram shader;
    private EntityEffectRenderer() {}

    public static void init(){
        CoreShaderRegistrationCallback.EVENT.register(context -> context.register(FifthMod.id("entity_effect"), VertexFormats.POSITION_COLOR, program -> shader = program));
        WorldRenderEvents.AFTER_ENTITIES.register(context -> render(context.matrixStack(), context.camera().getPos(), context.tickDelta()));
    }
    public static void update(EntityEffectManager.Config c){try{UUID u=UUID.fromString(c.uuid);if("off".equals(c.type))CONFIGS.remove(u);else CONFIGS.put(u,c);}catch(Exception ignored){}}

    private static void render(MatrixStack matrices, Vec3d camera, float tickDelta){
        if(shader==null||matrices==null||CONFIGS.isEmpty())return;
        MinecraftClient client=MinecraftClient.getInstance();if(client.world==null||client.player==null)return;
        Box search=client.player.getBoundingBox().expand(128);
        List<Entity> loaded=new ArrayList<>();loaded.add(client.player);loaded.addAll(client.world.getOtherEntities(client.player,search,e->CONFIGS.containsKey(e.getUuid())));
        for(Entity e:loaded){EntityEffectManager.Config cfg=CONFIGS.get(e.getUuid());if(cfg==null)continue;drawOne(matrices,camera,e,cfg,tickDelta);}
    }
    private static void drawOne(MatrixStack matrices,Vec3d camera,Entity e,EntityEffectManager.Config cfg,float tickDelta){
        Vec3d lp=e.getLerpedPos(tickDelta);
        double ix=lp.x-camera.x+cfg.offsetX;
        double iy=lp.y-camera.y+cfg.offsetY;
        double iz=lp.z-camera.z+cfg.offsetZ;
        matrices.push();matrices.translate(ix,iy,iz);matrices.multiply(MinecraftClient.getInstance().gameRenderer.getCamera().getRotation());
        RenderSystem.enableBlend();RenderSystem.defaultBlendFunc();RenderSystem.disableCull();RenderSystem.depthMask(false);RenderSystem.setShader(()->shader);
        float time=(System.currentTimeMillis()%100000L)/1000f;
        if(shader.getUniform("FivenTime")!=null)shader.getUniform("FivenTime").set(time);
        if(shader.getUniform("EffectKind")!=null)shader.getUniform("EffectKind").set("eyes".equals(cfg.type)?1f:0f);
        Matrix4f m=matrices.peek().getPositionMatrix();
        int a=(cfg.color>>>24)&255,r=(cfg.color>>>16)&255,g=(cfg.color>>>8)&255,b=cfg.color&255;
        if("eyes".equals(cfg.type))drawEyes(m,e.getHeight(),r,g,b,a,cfg.intensity,time);else drawDark(m,e.getWidth(),e.getHeight(),cfg.intensity,time);
        RenderSystem.depthMask(true);RenderSystem.enableCull();RenderSystem.disableBlend();matrices.pop();
    }
    private static void drawDark(Matrix4f m,float width,float height,float intensity,float time){
        BufferBuilder bb=Tessellator.getInstance().getBuffer();bb.begin(VertexFormat.DrawMode.QUADS,VertexFormats.POSITION_COLOR);
        float bodyW=Math.max(.45f,width*.9f),h=Math.max(1.2f,height),alpha=Math.min(.82f,.42f*intensity);
        quad(bb,m,-bodyW*.42f,.15f,bodyW*.42f,h*.72f,4,4,6,(int)(255*alpha));
        float head=.28f+Math.min(.16f,width*.15f);quad(bb,m,-head,h*.68f,head,h*.68f+head*2,2,2,3,(int)(255*alpha));
        // Shader-rendered rising fragments: generated quads, deliberately not Minecraft particles.
        for(int i=0;i<8;i++){float phase=(time*.45f+i*.137f)%1f;float yy=h*(.55f+phase*.85f);float xx=(float)Math.sin(i*2.17+time*1.1)*bodyW*.42f;float s=.035f+.03f*(i%3);int aa=(int)(150*(1f-phase)*Math.min(1.5f,intensity));quad(bb,m,xx-s,yy,xx+s,yy+s*2,5,5,7,Math.max(0,aa));}
        BufferRenderer.drawWithGlobalProgram(bb.end());
    }
    private static void drawEyes(Matrix4f m,float height,int r,int g,int b,int a,float intensity,float time){
        BufferBuilder bb=Tessellator.getInstance().getBuffer();bb.begin(VertexFormat.DrawMode.QUADS,VertexFormats.POSITION_COLOR);
        float y=height*.82f,sep=.105f,w=.07f,h=.035f,pulse=.75f+.25f*(float)Math.sin(time*6f),mul=Math.min(2.5f,intensity)*pulse;
        int rr=Math.min(255,(int)(r*mul)),gg=Math.min(255,(int)(g*mul)),bbv=Math.min(255,(int)(b*mul)),aa=Math.min(255,(int)(a*Math.min(1f,.75f*intensity)));
        // ring made from four tiny shader quads per eye; roughly 2x1 pixel proportion.
        eyeRing(bb,m,-sep,y,w,h,rr,gg,bbv,aa);eyeRing(bb,m,sep,y,w,h,rr,gg,bbv,aa);
        BufferRenderer.drawWithGlobalProgram(bb.end());
    }
    private static void eyeRing(BufferBuilder bb,Matrix4f m,float cx,float cy,float w,float h,int r,int g,int b,int a){
        float t=.012f;quad(bb,m,cx-w,cy-h,cx+w,cy-h+t,r,g,b,a);quad(bb,m,cx-w,cy+h-t,cx+w,cy+h,r,g,b,a);quad(bb,m,cx-w,cy-h,cx-w+t,cy+h,r,g,b,a);quad(bb,m,cx+w-t,cy-h,cx+w,cy+h,r,g,b,a);
    }
    private static void quad(BufferBuilder bb,Matrix4f m,float x1,float y1,float x2,float y2,int r,int g,int b,int a){bb.vertex(m,x1,y1,0).color(r,g,b,a).next();bb.vertex(m,x2,y1,0).color(r,g,b,a).next();bb.vertex(m,x2,y2,0).color(r,g,b,a).next();bb.vertex(m,x1,y2,0).color(r,g,b,a).next();}
}
